# Generated by Django 4.2.6 on 2023-10-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
