# Generated by Django 4.2.6 on 2023-10-07 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('loan_type', models.CharField(choices=[('Car', 'Car Loan'), ('Home', 'Home Loan'), ('Education', 'Education Loan'), ('Personal', 'Personal Loan')], max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_period', models.PositiveIntegerField()),
                ('disbursement_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
