# Generated by Django 4.2.6 on 2023-10-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApplication', '0002_loan_emi_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='total_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
