# Generated by Django 4.2.6 on 2023-10-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApplication', '0003_loan_total_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
    ]
