# Generated by Django 4.2.6 on 2023-10-08 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registerPayment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='loan_id',
            new_name='Loan_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
