# Generated by Django 4.2.6 on 2023-10-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerPayment', '0002_rename_amount_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Interest_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='Principal_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
